### ISSUE TITLE
Compatibility with original branch panel?

### ISSUE THREAD

**Issue by zerbian** [MiguelDeTrool/Offshoots#1]
Hey there, I recently discovered this repo and was wondering if this diy clone is compatible with the original board design. Can I use the original panel with the pcbs ?

Thank you!

**Comment by MiguelDeTrool** [comment]
Hello! It might just fit into to an original panel, but I wouldn't recommend it. The jacks would be slightly wonky, as they are a bit more spaced out horizontally on the original. Also, the button diameter is slightly different. I use 6mm, the original uses 5mm. You would have to either find different button caps, which wouldn't be easy, or drill the original panel a slight bit.

**Comment by zerbian** [comment]
Okay, thank you, good to know!
